version: '2'
services:
  client:
    # Step 1 - Point build step to the client directory
    build: '.'
    ports:
      # Step 2 - Add the port that the client application runs on - (port:port).
      - '3000:3000'
